# roles/delete-namespace/main.yml

- name: Check namespace exists
  shell: oc projects
  register: namespace_check_result
  ignore_errors: true

- name: Delete Namespace
  shell:
    cmd: oc delete project {{ namespace_name }}
  when: 'namespace_name in namespace_check_result.stdout'
