apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dev-csv-service
    pipeline: development
  name: dev-csv-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: dev-csv-service
    deploymentconfig: dev-csv-service
    pipeline: development
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: dev-csv-service
        deploymentconfig: dev-csv-service
        pipeline: development
    spec:
      containers:
        - env:
            - name: DATA_FOLDER
              value: /data
          image: >-
            docker-registry.default.svc:5000/csv-dev/dev-csv-s2i-build:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: dev-csv-service
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /csv/api/v1
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: dev-csv-data
  test: false
  triggers: []