---
- name: Check limit range exists
  shell: "oc get limitrange -n {{ namespace }} | grep compute-resource-limits"
  register: limit_range_check_result

- name: Delete limitrange
  shell: "oc delete limitrange compute-resource-limits -n {{ namespace }}"
  when: limit_range_check_result.rc == 0

- name: Create limit range
  command: "oc create limitrange {{ playbook_dir }}/files/compute-limitrange.yaml -n {{ namespace }}"