apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resource-limits
spec:
  limits:
  - max:
      cpu: "1"
      memory: 4Gi
    min:
      cpu: 300m
      memory: 500Mi
    type: Pod
  - default:
      cpu: 500m
      memory: 500Mi
    defaultRequest:
      cpu: 200m
      memory: 200Mi
    max:
      cpu: "1"
      memory: 4Gi
    maxLimitRequestRatio:
      cpu: "5"
    min:
      cpu: 200m
      memory: 100Mi
    type: Container
