---
- name: Clean up CSV-Service CI/CD environment
  hosts: openshift
  gather_facts: no
  roles:
  - openshift-login

  tasks:
  - name: Delete build namespace
    include_role: 
      name: delete-namespace
    vars:
      namespace_name: "{{ build_namespace }}"
  - name: Delete development namespace
    include_role:
      name: delete-namespace
    vars:
      namespace_name: "{{ dev_namespace }}"
  - name: Delete test namespace
    include_role:
      name: delete-namespace
    vars:
      namespace_name: "{{ test_namespace }}"
  - name: Delete production namespace
    include_role:
      name: delete-namespace
    vars:
      namespace_name: "{{ prod_namespace }}"

