apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: csv-service
  name: csv-service
spec:
  host: csvservice-myproject.127.0.0.1.nip.io
  path: /
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: csv-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2017-10-23T12:59:24Z
      status: "True"
      type: Admitted
    host: csvservice-myproject.127.0.0.1.nip.io
    routerName: router
    wildcardPolicy: None
